pipeline {
    agent any
    stages {
        stage('Checkout') {
                steps {
                 git credentialsId: '', url: 'https://github.com/theRealnoumanshah/dotnetcore.git', branch: 'master'
                 }
            }
        stage('Restore packages'){
           steps{
              bat "dotnet restore TodoApi.Swashbuckle\\TodoApi.csproj"
             }
          }
        stage('Clean'){
            steps{
                bat "dotnet clean TodoApi.Swashbuckle\\TodoApi.csproj"
             }
           }
        stage('Build'){
           steps{
              bat "dotnet build TodoApi.Swashbuckle\\TodoApi.csproj --configuration Release"
            }
         }      
        stage('Publish'){
             steps{
               bat "dotnet publish TodoApi.Swashbuckle\\TodoApi.csproj"
             }
}        
}
